language: node_js
sudo: false
cache: yarn
node_js: 13
script: yarn lint && yarn lint:css && yarn test:ci && yarn build
deploy:
  provider: heroku
  app: tic-tac-bumm
  api_key:
    secure: Rc0QCt0KAIA5y3kNT12tbQGqc44WQHQOXP8899dFQuTc8Y47jQgy+RVT7q0TChwKPEcF6nfXnTHsRJWjrwGnfUaa9DFa3EiDFdXYqvD4kJKB1uOgHMBhaDUqKU5quOV06WdmhELs40REHq9PG18sIAvV+sqpXo+OylCzymStOyuHCeSqpeV/5/dtFlAGkpKMCagVnWT2ai9LKkCNaBN6VYQHMcvwiTRIpSftdsJu1YehU54rPsQONo5RGMLVmyQkMxVHs/ZG1g/XGWquDaz7kK6yLIjE+6pC6ia4FeScIsACfpnQI1nxK/P3xZLdzXUz0JvWishg4Tuoomtoo0PaVOk8tiKe/EmG5APkcu1Cc/JgAS/Hl0yg1zkqzKuGdo6QTk+Rayuex/rUgqn0iQ14uJJAjY7XOiTnxbpnwEj6K6SFIKzcucLjQ5S/Ozkt1+Hx08/kWJ/3sRUqeRKszzBjJUyxoTcQT/qoX4q4u7J1fiSwYAw+5vvOk81hff7/8+6oMXrPV3BdS1j9AHmeEiJQXyTNLyM+ZziigEvihwBcjUA3n2sYKYjh9aK0Vc5UDsgtDXb0gepiGZw8MIbNtxa3+5PqlZe9xjDTZEzGiFBAA/qH/r1WATf0upFXMixRzPS3X3W9t/PlWLE1anKuK8b88pL3ip4H/XXjmWULOObUPHM=
