language: node_js
sudo: false
cache: yarn
node_js: 13
script: yarn lint && yarn lint:css && yarn test:ci && yarn build
deploy:
  provider: heroku
  app: tic-tac-bumm
  api_key:
    secure: zJfkU8wyN1X0EfezGSufJpxfQHvBubzIp96viMvuSqzP2s+5T/A7NfrKZUy9+QRGVNpQluVPEYrW0MmBXd8Aw6PBSNILlvv1UnEY6uZRpJyjoSzdR21lOfKR3c5C13/I07OqHL6P7p4877FZviRGHK0qRVzsBwC+1wHQ5cIZiIAuLZvjusEI/gSdOoPqQETtEc0bxgP80Uknhclx5xDteDl+grDeWGJnCUHRVNl8CoxiZkPX18xxtLYIQU+gTWKgQR1GP2tHY5QKw3yQCoOSRe9UrFJrfhzMf5IK2oCkKpyFT3FDOJI9u/ApTq27wUI86cUiVdm6g8jcaPLzzpXPWy/UTMrGlZNL++7+r8SYsjCqTgOAl+SeKbsONI5KNpVMrQUiWX0QkdwwaRfw2eOFos/Rh8Oa4JDk/zchesS/LAKpUBz/1jXUDsRnZldcBMckyDgbgLGCsIxHxw/DXQeClXW7qYamGuZIjOvgfIRdG8vKU2SCuGYJNPDuWZwyOKcgchtX+YURIstUX28JvmR51Q2tMgddwQcdllY0U7Ax42W9dfB7r44Z5/JhzMGjPTi+dWx/15yCGxaL2XTBIDjUnaZi7fxkH46GFMVdXBq1O7cq+QFQ3zJhYMW8r0I9/p1ZzsjJjs8MI+UqatvicRTlDd2D3A6ts2JqHbMmX8AovgE=
